# Intepolabilidad de DataFrame con Función NumPy
__Pandas__ está integrada con __Numpy__ en su mayoría, dado que la gran parte de funciones NumPy pueden llamarse directamente sobre objetos ```Series``` o ```DataFrame```.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Preparación de DataFrame de ejemplo
np.random.seed(42)
df_ejemplo = pd.DataFrame(np.random.randn(5, 4), columns=["A", "B", "C", "D"])
print("📊 DataFrame Original (5x4):")
print(df_ejemplo)


📊 DataFrame Original (5x4):
          A         B         C         D
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304


# 1. Aplicación de funciones universales (ufuncs) 🧮
Las funciones universales de NumPy (ufuncs) se aplican elemento por elementos a los ```DataFrames``` y ```Series```, manteniendo sus estructuras intactas.

### 1.1. Aplicamos la función exponenciad de Numpy ```np.exp()```🚀

In [5]:
df_ejemplo_exp = np.exp(df_ejemplo)
print(f'Resultado:\n{df_ejemplo_exp}')

Resultado:
          A         B         C         D
0  1.643313  0.870868  1.911118  4.586099
1  0.791240  0.791253  4.851136  2.154233
2  0.625331  1.720406  0.629130  0.627677
3  1.273746  0.147595  0.178188  0.569904
4  0.363189  1.369228  0.403320  0.243581


### 1.2. Conversión a Array de NumPy 🧱

In [6]:
array_puro = np.asarray(df_ejemplo)
print(f'Tipo de objeto resultante:\n{ type(array_puro) }')
print('=' * 50)
print(f'Array puro, sin etiquetas:\n{ array_puro }')

Tipo de objeto resultante:
<class 'numpy.ndarray'>
Array puro, sin etiquetas:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]


## 2. Alineación en funciones con multiples Series 🧩
cuando se pasa __más de una Serie__ a un función ```ufunc``` de NumPy, Pandas realiza la alineación automática por etiqueta antes de ejecutar la operación.

In [7]:
#A. Alineación por etiquetas desordenadas
# 📦 Series con el mismo índice, pero desordenado
ser1 = pd.Series([34, 20, 10], index=["a", "b", "c"])
ser2 = pd.Series([3, 5, 2], index=["b", "a", "c"]) # 'a' y 'b' están cambiados

print(f'📋 Series 1:\n{ser1}' )
print('=' * 35)
print(f'📋 Series 2 (Desordenada):\n{ser2}')
print('=' * 35)
# Se realiza un alineado por etiqueta
residuo_alineado = np.remainder(ser1, ser2)
print(f'Resultado de np.remainder():\n{ residuo_alineado }')

📋 Series 1:
a    34
b    20
c    10
dtype: int64
📋 Series 2 (Desordenada):
b    3
a    5
c    2
dtype: int64
Resultado de np.remainder():
a    4
b    2
c    0
dtype: int64


In [9]:
#B. Manejo de Nan y unión de índices
ser3 = pd.Series([2, 4, 6], index=["b", "c", "d"])
print(f'Serie 1:\n{ ser1 }')
print('=' * 40)
print(f'Serie 2:\n{ser2}')
print('=' * 40)
residuos_nan = np.remainder(ser1, ser3)
print(f'Resultado de np.remainder(ser1, ser3):\n{ residuos_nan }')

Serie 1:
a    34
b    20
c    10
dtype: int64
Serie 2:
b    3
a    5
c    2
dtype: int64
Resultado de np.remainder(ser1, ser3):
a    NaN
b    0.0
c    2.0
d    NaN
dtype: float64


## 3. Prioridad: Serie vs Index ⚖️

In [11]:
# No hay alineación por etiquetas , los compara por posiicones
s_valores = pd.Series([1, 2, 3])
idx_valores = pd.Index([4, 5, 0])
print(f'Serie:\n{s_valores}')
print('=' * 60)
print(f'Index:\n{idx_valores}')
print('=' * 60)

#np.maximum compara elemento a elemento y devuelve el mayor entre de los dos
maximos = np.maximum(s_valores, idx_valores)
print(f'✨Resultado de np.maximums(s_valores, idx_valores):\n{maximos}')
print('=' * 60)
print( type(maximos) )

Serie:
0    1
1    2
2    3
dtype: int64
Index:
Index([4, 5, 0], dtype='int64')
✨Resultado de np.maximums(s_valores, idx_valores):
0    4
1    5
2    3
dtype: int64
<class 'pandas.core.series.Series'>
